# Generated by Django 6.0 on 2026-01-07 18:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='created',
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('open', 'Открыта'), ('closed', 'Закрытая')], default='draft', max_length=6),
        ),
    ]
