# Generated by Django 6.0 on 2026-01-07 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_vacancy_created_vacancy_slug_vacancy_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='created',
        ),
    ]
