# Generated by Django 6.0 on 2026-01-07 18:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_remove_vacancy_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
